site_name: The only Documentation you'll ever need!
theme:
  name: bootstrap386
  features:
    - markdown.extensions.codehilite
    - markdown.extensions.toc
    - markdown.extensions.wikilinks

nav:
  - Home: 'index.md'
  - Projects: '/projects/index.md'
    - Bruteforcer: '/projects/bruteforcer.md'
