site_name: The only Documentation you'll ever need!
theme:
  name: bootstrap386
  features:
    - markdown.extensions.codehilite
    - markdown.extensions.toc
    - markdown.extensions.wikilinks

nav:
  - Home: /docs/index.md
  - Projects:
    - Home: /docs/projects/index.md
    - Bruteforcer: /docs/projects/bruteforcer.md
